name: Java Security Scan

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run OWASP Dependency Check
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      run: mvn org.owasp:dependency-check-maven:12.1.3:check

    - name: Run SpotBugs
      run: mvn com.github.spotbugs:spotbugs-maven-plugin:4.9.4.2:check