name: Java Security Scan

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create reports directory
        run: mkdir -p security-reports

      - name: Run OWASP Dependency Check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mvn org.owasp:dependency-check-maven:12.1.3:check \
            -Dnvd.api.key="$NVD_API_KEY" \
            -DdependencyCheck.outputDirectory=./security-reports \
            -DdependencyCheck.format=HTML,JSON,XML

      - name: Run SpotBugs with custom output
        run: |
          mvn com.github.spotbugs:spotbugs-maven-plugin:4.9.4.2:spotbugs \
            -Dspotbugs.outputDirectory=./security-reports \
            -Dspotbugs.outputFile=spotbugs-report.xml \
            -Dspotbugs.htmlOutputFile=spotbugs-report.html

      - name: List generated files (for debugging)
        run: |
          echo "Files in security-reports:"
          ls -la security-reports/
          echo "Files in target directory:"
          find . -name "*.html" -o -name "*.xml" -o -name "*.json" | head -20

      - name: Copy Dependency Check reports to security-reports
        run: |
          cp target/dependency-check-report.html security-reports/ 2>/dev/null || true
          cp target/dependency-check-report.json security-reports/ 2>/dev/null || true
          cp target/dependency-check-report.xml security-reports/ 2>/dev/null || true

      - name: Upload all security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            security-reports/*.html
            security-reports/*.xml
            security-reports/*.json
          if-no-files-found: warn